version: "2"
services:
  web:
    container_name: nestjs-monorepo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5870:5870"
    env_file: .env
    volumes:
      - .:/src:cached